name: Dynmap Automation

on:
  workflow_dispatch:
  schedule:
    - cron: '0,30 * * * *'

jobs:
  update-dynmap-images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }} # Ensure the token is set properly for checkout

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dynmap_lens

    - name: Create assets directory
      run: mkdir -p assets
      
    - name: Capture cr spawn
      run: |
        timestamp=$(date +"%Y-%m-%d-%H-%M-%S")
        dynmap-lens.py -v https://dynmap.cubekrowd.net/ creative flat [0,64,0] [1,1] 5 assets/Spawn-${timestamp}.png

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add assets/*
        git commit -m "Update dynmap images"
        git push origin HEAD
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
